# Use a lightweight Node.js image
FROM node:alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm install --force

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Start the application
CMD ["npm", "start"]
